# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bureau-ios-device-bb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bureau-ios-device-bb
#	pod 'bureau-id-fraud-sdk' , '2.0.2'
  pod 'bureau-id-fraud-sdk', :path => '/Users/apple/Documents/Hari/bureau_git/bureau-id-fraud-sdk'
  pod 'DGCharts'

  target 'bureau-ios-device-bbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bureau-ios-device-bbUITests' do
    # Pods for testing
  end
      
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "Sentry" || target.name == "SwiftProtobuf" then
        config.build_settings["BUILD_LIBRARY_FOR_DISTRIBUTION"] = 'YES'
      end
    end
  end
end
